name: Deploy Go App

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверяем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Устанавливаем Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Сборка бинарника
      - name: Build binary
        run: |
          pwd
          ls -la
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/base


      # Подключение к серверу по SSH и деплой
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p /var/www/myapp
            rm -f /var/www/myapp/main
            exit || true
      - name: Upload binary
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: main
          target: /var/www/myapp/main

      # Перезапуск сервиса
      - name: Restart service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo systemctl restart myapp
            sudo systemctl status myapp
